# Generated by Django 4.2.26 on 2025-11-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='media_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show')], default='movie', max_length=8),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
